In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
pd.DataFrame

pandas.core.frame.DataFrame

In [5]:
my_list = [14, 4, 34, 56, 78, 55]
my_list

[14, 4, 34, 56, 78, 55]

In [9]:
my_first_df = pd.DataFrame({"pairs of shoes": my_list})

In [10]:
my_first_df

   pairs of shoes
0              14
1               4
2              34
3              56
4              78
5              55

In [11]:
json_option_1 =[{ 'a': 3, 'b': 4, 'c': 7}, { 'a': 9, 'b': 14, 'c': 20}]
json_option_2 = {'a': [3, 9], 'b': [4,14], 'c': [7,20]}

In [12]:
type(json_option_1)

list

In [13]:
len(json_option_1)

2

In [14]:
json_option_1[0]

{'a': 3, 'b': 4, 'c': 7}

In [15]:
json_option_1[1]

{'a': 9, 'b': 14, 'c': 20}

In [17]:
json_option_1[0]['a']

3

In [18]:
json_option_1[0]['c']

7

In [19]:
json_option_1[1]['b']

14

In [20]:
df_1 = pd.DataFrame(json_option_1)
df_1

   a   b   c
0  3   4   7
1  9  14  20

In [21]:
type(json_option_2)

dict

In [22]:
len(json_option_2)

3

In [23]:
json_option_2.keys()

dict_keys(['a', 'b', 'c'])

In [24]:
json_option_2['b']

[4, 14]

In [25]:
type(json_option_2['b'])

list

In [26]:
json_option_2['b'][1]

14

In [28]:
df_2 = pd.DataFrame(json_option_2)
df_2

   a   b   c
0  3   4   7
1  9  14  20

In [29]:
df_2['a']

0    3
1    9
Name: a, dtype: int64

In [30]:
df_2['a'].loc[0]

3

In [31]:
df_2['a'].iloc[0]

3

In [32]:
ls

PandasChallenge_Ibrayeva.ipynb  ibrayeva_SystemsCheck.ipynb
cces_example_data.csv

In [33]:
cces = pd.read_csv('cces_example_data.csv')

In [34]:
cces

,pew_religimp,pew_churatd,sex,educ,nonwhite,age,faminc_new,pid3,ideo5,QueerPhobia,...,InterGBiasParty,InterGBiasCand,InterGBiasSup,LibMediaUse,ConMediaUse,Real_Threat,Symb_Threat,Evaluation,teamweight,caseid
0,2,6,2,2,1,56,6,1,1,1.000000,...,-99,-99,-96,2.666667,1.000000,5.00,4.857143,0,0.505028,1231308943
1,2,4,2,5,1,53,13,1,2,3.000000,...,-100,-100,-100,2.000000,2.000000,5.00,5.000000,0,0.852381,1232300315
2,1,2,1,2,1,69,10,2,5,4.333333,...,99,99,96,1.000000,1.000000,5.00,5.000000,2,1.320189,1232358697
3,2,3,1,6,1,76,97,1,3,1.000000,...,-86,-91,-89,4.666667,1.333333,4.25,4.428571,0,0.519198,1232540961
4,4,5,2,6,1,83,4,1,2,1.000000,...,-80,-88,-87,4.666667,3.666667,4.25,5.000000,0,1.154005,1232580601
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
654,1,5,2,2,2,30,4,1,1,2.666667,...,-79,-90,-67,1.666667,1.666667,3.00,3.000000,3,1.182346,1259989749
655,2,2,1,4,1,19,97,1,1,1.000000,...,-49,-25,-7,2.666667,1.000000,3.75,4.714286,0,0.660217,1260782541
656,4,6,1,3,1,20,7,1,1,1.000000,...,-47,-47,-41,4.666667,4.666667,5.00,4.285714,0,1.027184,1260840787
657,2,2,1,3,1,23,5,2,4,3.666667,...,40,99,94,2.000000,2.333333,2.50,3.000000,2,1.433068,1261039231
658,2,2,1,3,1,23,5,2,4,3.666667,...,40,99,94,2.000000,2.333333,2.50,3.000000,2,1.433068,1261039231

In [35]:
cces.head()

,pew_religimp,pew_churatd,sex,educ,nonwhite,age,faminc_new,pid3,ideo5,QueerPhobia,...,InterGBiasParty,InterGBiasCand,InterGBiasSup,LibMediaUse,ConMediaUse,Real_Threat,Symb_Threat,Evaluation,teamweight,caseid
0,2,6,2,2,1,56,6,1,1,1.000000,...,-99,-99,-96,2.666667,1.000000,5.00,4.857143,0,0.505028,1231308943
1,2,4,2,5,1,53,13,1,2,3.000000,...,-100,-100,-100,2.000000,2.000000,5.00,5.000000,0,0.852381,1232300315
2,1,2,1,2,1,69,10,2,5,4.333333,...,99,99,96,1.000000,1.000000,5.00,5.000000,2,1.320189,1232358697
3,2,3,1,6,1,76,97,1,3,1.000000,...,-86,-91,-89,4.666667,1.333333,4.25,4.428571,0,0.519198,1232540961
4,4,5,2,6,1,83,4,1,2,1.000000,...,-80,-88,-87,4.666667,3.666667,4.25,5.000000,0,1.154005,1232580601

In [36]:
cces.tail()

,pew_religimp,pew_churatd,sex,educ,nonwhite,age,faminc_new,pid3,ideo5,QueerPhobia,...,InterGBiasParty,InterGBiasCand,InterGBiasSup,LibMediaUse,ConMediaUse,Real_Threat,Symb_Threat,Evaluation,teamweight,caseid
654,1,5,2,2,2,30,4,1,1,2.666667,...,-79,-90,-67,1.666667,1.666667,3.00,3.000000,3,1.182346,1259989749
655,2,2,1,4,1,19,97,1,1,1.000000,...,-49,-25,-7,2.666667,1.000000,3.75,4.714286,0,0.660217,1260782541
656,4,6,1,3,1,20,7,1,1,1.000000,...,-47,-47,-41,4.666667,4.666667,5.00,4.285714,0,1.027184,1260840787
657,2,2,1,3,1,23,5,2,4,3.666667,...,40,99,94,2.000000,2.333333,2.50,3.000000,2,1.433068,1261039231
658,2,2,1,3,1,23,5,2,4,3.666667,...,40,99,94,2.000000,2.333333,2.50,3.000000,2,1.433068,1261039231

In [37]:
cces.head(13)

,pew_religimp,pew_churatd,sex,educ,nonwhite,age,faminc_new,pid3,ideo5,QueerPhobia,...,InterGBiasParty,InterGBiasCand,InterGBiasSup,LibMediaUse,ConMediaUse,Real_Threat,Symb_Threat,Evaluation,teamweight,caseid
0,2,6,2,2,1,56,6,1,1,1.000000,...,-99,-99,-96,2.666667,1.000000,5.00,4.857143,0,0.505028,1231308943
1,2,4,2,5,1,53,13,1,2,3.000000,...,-100,-100,-100,2.000000,2.000000,5.00,5.000000,0,0.852381,1232300315
2,1,2,1,2,1,69,10,2,5,4.333333,...,99,99,96,1.000000,1.000000,5.00,5.000000,2,1.320189,1232358697
3,2,3,1,6,1,76,97,1,3,1.000000,...,-86,-91,-89,4.666667,1.333333,4.25,4.428571,0,0.519198,1232540961
4,4,5,2,6,1,83,4,1,2,1.000000,...,-80,-88,-87,4.666667,3.666667,4.25,5.000000,0,1.154005,1232580601
5,4,6,1,3,2,87,9,3,3,4.000000,...,-39,-89,-84,4.000000,2.000000,4.00,3.714286,0,0.675546,1232638601
6,2,3,1,6,1,83,11,3,3,2.333333,...,-18,-79,-43,5.000000,4.000000,4.00,3.857143,0,0.519198,1232661775
7,1,1,1,5,1,69,11,3,4,4.666667,...,82,98,99,1.666667,5.000000,5.00,4.857143,2,0.954665,1232900901
8,1,2,1,6,1,84,10,3,3,2.666667,...,-61,-86,-49,2.666667,2.000000,3.75,3.285714,0,0.519198,1232924457
9,3,4,2,4,1,63,8,1,1,1.000000,...,-93,-98,-84,4.000000,1.333333,2.75,3.714286,0,0.873552,1233866717
10,1,1,1,3,2,54,2,2,4,3.666667,...,94,97,93,1.000000,3.000000,4.25,4.000000,3,1.081529,1234800933
11,2,3,2,5,1,46,6,1,2,2.666667,...,-84,-99,-91,5.666667,2.333333,4.25,4.714286,0,0.852381,1234814929
12,2,5,2,3,1,49,5,3,5,1.666667,...,92,97,94,2.000000,2.666667,3.25,3.000000,2,1.218731,1234833015

In [38]:
cces.tail(10)

,pew_religimp,pew_churatd,sex,educ,nonwhite,age,faminc_new,pid3,ideo5,QueerPhobia,...,InterGBiasParty,InterGBiasCand,InterGBiasSup,LibMediaUse,ConMediaUse,Real_Threat,Symb_Threat,Evaluation,teamweight,caseid
649,4,6,2,2,1,72,11,1,2,1.000000,...,-78,-100,-100,2.666667,1.333333,5.00,5.000000,0,0.764376,1259700847
650,4,6,2,6,1,29,6,3,3,3.333333,...,23,39,45,2.000000,2.666667,4.00,3.285714,2,0.944356,1259882317
651,4,6,2,2,1,31,1,3,6,1.333333,...,-1,47,47,1.333333,1.333333,3.00,3.000000,1,0.569765,1259936547
652,4,6,2,2,1,36,8,3,2,2.000000,...,26,82,49,3.000000,3.000000,3.00,4.000000,2,0.848605,1259953803
653,2,5,2,2,1,58,7,3,4,3.000000,...,71,66,62,1.666667,3.000000,3.50,3.571429,3,0.704586,1259985453
654,1,5,2,2,2,30,4,1,1,2.666667,...,-79,-90,-67,1.666667,1.666667,3.00,3.000000,3,1.182346,1259989749
655,2,2,1,4,1,19,97,1,1,1.000000,...,-49,-25,-7,2.666667,1.000000,3.75,4.714286,0,0.660217,1260782541
656,4,6,1,3,1,20,7,1,1,1.000000,...,-47,-47,-41,4.666667,4.666667,5.00,4.285714,0,1.027184,1260840787
657,2,2,1,3,1,23,5,2,4,3.666667,...,40,99,94,2.000000,2.333333,2.50,3.000000,2,1.433068,1261039231
658,2,2,1,3,1,23,5,2,4,3.666667,...,40,99,94,2.000000,2.333333,2.50,3.000000,2,1.433068,1261039231

In [39]:
cces.columns

Index(['pew_religimp', 'pew_churatd', 'sex', 'educ', 'nonwhite', 'age',
       'faminc_new', 'pid3', 'ideo5', 'QueerPhobia', 'ImmiPhobia',
       'InterGBiasParty', 'InterGBiasCand', 'InterGBiasSup', 'LibMediaUse',
       'ConMediaUse', 'Real_Threat', 'Symb_Threat', 'Evaluation', 'teamweight',
       'caseid'],
      dtype='object')

In [40]:
cces.shape

(659, 21)

In [41]:
cces.index

RangeIndex(start=0, stop=659, step=1)

In [42]:
len(cces.index)

659

In [43]:
cces['age']

0      56
1      53
2      69
3      76
4      83
       ..
654    30
655    19
656    20
657    23
658    23
Name: age, Length: 659, dtype: int64

In [44]:
cces['age'].mean()

52.180576631259484

In [45]:
cces.iloc[0]

pew_religimp       2.000000e+00
pew_churatd        6.000000e+00
sex                2.000000e+00
educ               2.000000e+00
nonwhite           1.000000e+00
age                5.600000e+01
faminc_new         6.000000e+00
pid3               1.000000e+00
ideo5              1.000000e+00
QueerPhobia        1.000000e+00
ImmiPhobia         1.000000e+00
InterGBiasParty   -9.900000e+01
InterGBiasCand    -9.900000e+01
InterGBiasSup     -9.600000e+01
LibMediaUse        2.666667e+00
ConMediaUse        1.000000e+00
Real_Threat        5.000000e+00
Symb_Threat        4.857143e+00
Evaluation         0.000000e+00
teamweight         5.050279e-01
caseid             1.231309e+09
Name: 0, dtype: float64

In [46]:
cces.iloc[15:20]

,pew_religimp,pew_churatd,sex,educ,nonwhite,age,faminc_new,pid3,ideo5,QueerPhobia,...,InterGBiasParty,InterGBiasCand,InterGBiasSup,LibMediaUse,ConMediaUse,Real_Threat,Symb_Threat,Evaluation,teamweight,caseid
15,1,1,1,3,1,77,6,3,4,5.000000,...,48,94,92,1.666667,3.000000,2.75,4.714286,2,1.054974,1234861823
16,4,6,2,4,1,61,9,3,3,2.000000,...,-42,-63,-75,1.000000,1.000000,2.00,2.000000,0,0.873552,1234863027
17,4,5,2,3,1,66,10,1,2,1.333333,...,-89,-88,-88,5.000000,2.333333,5.00,4.428571,0,1.092339,1234946769
18,4,6,1,2,1,67,8,1,3,2.666667,...,-85,-92,-95,4.333333,2.000000,3.25,4.000000,0,0.946275,1234991753
19,1,6,2,3,1,44,3,2,5,5.000000,...,96,90,-1,3.000000,3.000000,1.50,2.714286,0,0.918231,1235109215

In [47]:
cces.iloc[658]

pew_religimp       2.000000e+00
pew_churatd        2.000000e+00
sex                1.000000e+00
educ               3.000000e+00
nonwhite           1.000000e+00
age                2.300000e+01
faminc_new         5.000000e+00
pid3               2.000000e+00
ideo5              4.000000e+00
QueerPhobia        3.666667e+00
ImmiPhobia         2.500000e+00
InterGBiasParty    4.000000e+01
InterGBiasCand     9.900000e+01
InterGBiasSup      9.400000e+01
LibMediaUse        2.000000e+00
ConMediaUse        2.333333e+00
Real_Threat        2.500000e+00
Symb_Threat        3.000000e+00
Evaluation         2.000000e+00
teamweight         1.433068e+00
caseid             1.261039e+09
Name: 658, dtype: float64

In [48]:
cces.iloc[-1]

pew_religimp       2.000000e+00
pew_churatd        2.000000e+00
sex                1.000000e+00
educ               3.000000e+00
nonwhite           1.000000e+00
age                2.300000e+01
faminc_new         5.000000e+00
pid3               2.000000e+00
ideo5              4.000000e+00
QueerPhobia        3.666667e+00
ImmiPhobia         2.500000e+00
InterGBiasParty    4.000000e+01
InterGBiasCand     9.900000e+01
InterGBiasSup      9.400000e+01
LibMediaUse        2.000000e+00
ConMediaUse        2.333333e+00
Real_Threat        2.500000e+00
Symb_Threat        3.000000e+00
Evaluation         2.000000e+00
teamweight         1.433068e+00
caseid             1.261039e+09
Name: 658, dtype: float64

In [49]:
subset_cces = cces.iloc[300:400]

In [50]:
subset_cces

,pew_religimp,pew_churatd,sex,educ,nonwhite,age,faminc_new,pid3,ideo5,QueerPhobia,...,InterGBiasParty,InterGBiasCand,InterGBiasSup,LibMediaUse,ConMediaUse,Real_Threat,Symb_Threat,Evaluation,teamweight,caseid
300,1,6,1,4,1,65,97,2,4,3.000000,...,18,87,90,1.000000,4.333333,5.00,3.857143,2,1.054974,1240322949
301,4,6,1,6,1,66,97,3,3,1.666667,...,-61,-60,-60,4.333333,1.000000,3.50,5.000000,0,0.519198,1240325313
302,1,2,1,6,1,57,9,1,1,1.000000,...,-47,-90,-79,3.333333,1.666667,2.50,4.000000,0,0.725682,1240325357
303,4,6,2,3,1,64,4,3,2,1.000000,...,-80,-79,-99,4.666667,4.666667,4.00,5.000000,0,0.873552,1240348917
304,4,6,1,6,1,64,8,1,3,2.333333,...,-70,-88,-76,3.000000,1.666667,4.25,3.714286,0,0.725682,1240349029
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,2,5,1,3,1,64,10,2,4,4.000000,...,50,100,100,1.000000,2.666667,4.50,4.857143,2,1.073830,1242499635
396,4,6,2,5,1,54,9,1,3,1.000000,...,-88,-99,-98,4.000000,1.000000,3.50,4.428571,0,0.852381,1242500387
397,4,4,2,6,1,37,3,1,1,1.000000,...,-55,-60,-70,2.666667,2.000000,3.50,4.142857,0,0.855743,1242525571
398,4,6,2,3,1,58,2,3,3,2.000000,...,-39,-67,-37,4.000000,1.666667,1.75,2.142857,0,0.873552,1242529769
399,4,6,1,5,1,41,10,1,2,2.000000,...,-77,-85,-87,4.333333,3.666667,4.50,4.714286,0,0.809208,1242530527

In [51]:
subset_cces.shape

(100, 21)

In [52]:
subset_cces.to_csv('subset_cces_example_data.csv')

In [53]:
ls

PandasChallenge_Ibrayeva.ipynb  ibrayeva_SystemsCheck.ipynb
cces_example_data.csv           subset_cces_example_data.csv

In [54]:
cces[['age', 'sex']]

     age  sex
0     56    2
1     53    2
2     69    1
3     76    1
4     83    2
..   ...  ...
654   30    2
655   19    1
656   20    1
657   23    1
658   23    1

[659 rows x 2 columns]

In [1]:
subset_cces1 = cces.iloc[['age', 'sex']]

NameError: name 'cces' is not defined